{% set version = "1.6.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-grates
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/grates_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/grates/grates_{{ version }}.tar.gz
  sha256: e290f77861511cab8e7ca0c7981820a16016f603dd3e61e4fe40973a41f7ff16

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-fastymd
  run:
    - r-base
    - r-fastymd

test:
  commands:
    - $R -e "library('grates')"           # [not win]
    - "\"%R%\" -e \"library('grates')\""  # [win]

about:
  home: https://www.reconverse.org/grates/
  dev_url: https://github.com/reconverse/grates
  license: MIT
  summary: Provides a coherent interface and implementation for creating grouped date classes. This package is part of the RECON (<https://www.repidemicsconsortium.org/>) toolkit for outbreak analysis.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan
