{% set version = "1.4.2" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-grates
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/grates_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/grates/grates_{{ version }}.tar.gz
  sha256: 552056520e2f6f43b99c7ddda52ac6c70767b550224c0ad2189e08dd81aa2803

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip  # [win]

  host:
    - r-base
    - r-clock
    - r-ellipsis
    - r-rlang
    - r-vctrs >=0.5.0

  run:
    - r-base
    - r-clock
    - r-ellipsis
    - r-rlang
    - r-vctrs >=0.5.0

test:
  commands:
    - $R -e "library('grates')"           # [not win]
    - "\"%R%\" -e \"library('grates')\""  # [win]

about:
  home: https://www.reconverse.org/grates/
  dev_url: https://github.com/reconverse/grates
  license: MIT
  summary: Provides a coherent interface and implementation for creating grouped date classes. This package is part of the RECON (<https://www.repidemicsconsortium.org/>) toolkit for outbreak analysis.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan
